/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package server;

import javax.swing.JOptionPane;

/**
 *
 * @author Rakesh
 */
public class ServerWindow extends javax.swing.JFrame {
	private String name;
	/**
	 * Creates new form ChatWindow
	 */
	public ServerWindow(String ip) {
		initComponents();
		setVisible(true);
		name=System.getenv("USERNAME");
		setTitle(JOptionPane.showInputDialog(null, "Enter Name : ", name)+" : "+ip);
		message.grabFocus();
	}
	public ServerWindow() {
		this("");
	}
	public String getMessage() {
		return message.getText();
	}
	public void addMessage(String sender, String msg) {
		log.insert(sender+" : "+msg+"\n", log.getText().length());
		log.setCaretPosition(log.getText().length());
	}
	public String getMessageLog() {
		return log.getText();
	}
	public void setMessageLog(String text) {
		log.setText(text);
		log.setCaretPosition(log.getText().length());
	}
	public String getSenderName() {
		return name;
	}
	public void onSendMessage(String msg) {}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        btn = new javax.swing.JButton();
        message = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NoName");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        log.setColumns(20);
        log.setEditable(false);
        log.setLineWrap(true);
        log.setRows(5);
        jScrollPane1.setViewportView(log);

        btn.setText("Send");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        message.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                messageKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(message)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
		addMessage(name, getMessage());
		onSendMessage(getMessage());
		message.setText("");
	}//GEN-LAST:event_btnActionPerformed

	private void messageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_messageKeyTyped
		if(evt.getKeyChar()=='\n')
			btn.doClick();
	}//GEN-LAST:event_messageKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea log;
    private javax.swing.JTextField message;
    // End of variables declaration//GEN-END:variables
}
